steps:

# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/paveway-academy-dev:${SHORT_SHA}', '.']
  
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/paveway-academy-dev:${SHORT_SHA}']
  
  # deploy container image to Cloud Run region Oregon
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'paveway-academy-dev', '--image', 'gcr.io/$PROJECT_ID/paveway-academy-dev:${SHORT_SHA}', '--cpu-boost', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']
  env:
  - 'PORT=8080'
  
images:
- gcr.io/$PROJECT_ID/paveway-academy-dev
serviceAccount: 'cloudbuild@paveway-academy.iam.gserviceaccount.com'
options:
  logging: CLOUD_LOGGING_ONLY
